spring:
  application:
    name: kukulkancraftsman
  messages:
    basename: i18n/messages
  data:
    mongodb:
      host: localhost
      port: 27117
      database: kukulkancraftsman
  jmx:
    enabled: false
  main:
    banner-mode: 'console'
kukulkan:
  config:
    inputdir: /home/daniel/git/
    outputdir: /home/daniel/git/
    documenturl: http://localhost/
    external-apps:
      modeler: http://localhost/dsl-core/
      presentation: http://localhost/kukulkan-presentation
      slides: http://localhost/data/slides.pdf
  data:
    mysql:
      uri: jdbc:mysql://kukulkancraftsman-mysql:3306
logging:
  file: logs/kukulkan.log
  level:
    root: info
    org.springframework.web: false
    org.hibernate: false
    org.hibernate.SQL: false
#pattern:
#    console: "[%green(%-5level)] : %white(%msg%n)"
#   file: "%d %-5level [%thread] %logger : %msg%n"
application:
  version: 1.0.0